import turtle
import math
import graphicssystem as gs

turtle.setup(720, 584)
turtle.setworldcoordinates(-3, -2, 3, (math.sqrt(3)+4)/2)
A = gs.Point(0, 0)
A.plot(label="A")
B = gs.Point(1, 0)
B.plot(label="B")
s1 = gs.Seg(A, B)
s1.plot()
c1 = gs.Circle(A, A.distance(B))
c1.plot()
c2 = gs.Circle(B, A.distance(B))
c2.plot()
p1, p2 = c1.intersection(c2)
C = gs.Point(p1.x, p1.y)
C.plot(label="C")
D = gs.Point(p2.x, p2.y)
D.plot(label="D")
s2 = gs.Seg(C, B)
s2.plot(c="red")
s3 = gs.Seg(B, D)
s3.plot(c="red")
c3 = gs.Circle(D, B.distance(D))
c3.plot()
p1, p2 = c3.intersection(c1)
E = gs.Point(p2.x, p2.y)
E.plot(label="E")
s4 = gs.Seg(D, E)
s4.plot(c="red")
c4 = gs.Circle(E, D.distance(E))
c4.plot()
p1, p2 = c4.intersection(c1)
F = gs.Point(p1.x, p1.y)
F.plot(label="F")
s5 = gs.Seg(E, F)
s5.plot(c="red")
c5 = gs.Circle(F, E.distance(F))
c5.plot()
p1, p2 = c5.intersection(c1)
G = gs.Point(p1.x, p1.y)
G.plot(label="G")
s6 = gs.Seg(F, G)
s6.plot(c="red")
s7 = gs.Seg(G, C)
s7.plot(c="red")
turtle.done()
