import turtle
import math
import graphicssystem as gs

turtle.setup(720, 577)
turtle.setworldcoordinates(-4, -2-math.sqrt(2), 4, 3)
O = gs.Point(0, 0)
O.plot(label="O")
c1 = gs.Circle(O, 1)
c1.plot()
A = gs.Point(-1, 0)
A.plot(label="A")
B = gs.Point(1, 0)
B.plot(label="B")
s1 = gs.Seg(A, B)
s1.plot()
c2 = gs.Circle(A, A.distance(B))
c2.plot()
c3 = gs.Circle(B, A.distance(B))
c3.plot()
p1, p2 = c2.intersection(c3)
q1 = gs.Point(p1.x, p1.y)
q2 = gs.Point(p2.x, p2.y)
s2 = gs.Seg(q1, q2)
s2.plot()
p1, p2 = s2.intersection(c1)
C = gs.Point(p1.x, p1.y)
C.plot(label="C")
D = gs.Point(p2.x, p2.y)
D.plot(label="D")
c4 = gs.Circle(A, A.distance(C))
c4.plot()
c5 = gs.Circle(C, A.distance(C))
c5.plot()
p1, p2 = c4.intersection(c5)
q = gs.Point(p1.x, p1.y)
l1 = gs.Line(q, O)
l1.plot(L=5)
p1, p2 = l1.intersection(c1)
E = gs.Point(p1.x, p1.y)
E.plot(label="E")
G = gs.Point(p2.x, p2.y)
G.plot(label="G")
c6 = gs.Circle(B, B.distance(C))
c6.plot()
p1, p2 = c6.intersection(c5)
q = gs.Point(p2.x, p2.y)
l2 = gs.Line(q, O)
l2.plot(L=5)
p1, p2 = l2.intersection(c1)
H = gs.Point(p1.x, p1.y)
H.plot(label="H")
F = gs.Point(p2.x, p2.y)
F.plot(label="F")
s3 = gs.Seg(A, E)
s3.plot(c="red")
s4 = gs.Seg(E, C)
s4.plot(c="red")
s5 = gs.Seg(C, F)
s5.plot(c="red")
s6 = gs.Seg(F, B)
s6.plot(c="red")
s7 = gs.Seg(B, G)
s7.plot(c="red")
s8 = gs.Seg(G, D)
s8.plot(c="red")
s9 = gs.Seg(D, H)
s9.plot(c="red")
s10 = gs.Seg(H, A)
s10.plot(c="red")
turtle.done()
