import turtle
import graphicssystem as gs

turtle.setup(720, 720)
turtle.setworldcoordinates(-5, -5, 5, 5)
O = gs.Point(0, 0)
O.plot(label="O")
c1 = gs.Circle(O, 1)
c1.plot(speed=0)
A = gs.Point(-1, 0)
A.plot(label="A")
B = gs.Point(1, 0)
B.plot(label="B")
s1 = gs.Seg(A, B)
s1.plot()
c2 = gs.Circle(A, A.distance(B))
c2.plot(speed=0)
c3 = gs.Circle(B, A.distance(B))
c3.plot(speed=0)
p1, p2 = c2.intersection(c3)
q1 = gs.Point(p1.x, p1.y)
q2 = gs.Point(p2.x, p2.y)
s2 = gs.Seg(q1, q2)
s2.plot()
p1, p2 = s2.intersection(c1)
C = gs.Point(p1.x, p1.y)
C.plot(label="C")
D = gs.Point(p2.x, p2.y)
D.plot(label="D")
turtle.done()
