import turtle
import math
import graphicssystem as gs

turtle.setup(720, 556)
turtle.setworldcoordinates(-4, -(4+math.sqrt(10-2*math.sqrt(5)))/2, 4, 3)
O = gs.Point(0, 0)
O.plot(label="O")
c1 = gs.Circle(O, 1)
c1.plot(speed=0)
A = gs.Point(-1, 0)
A.plot(label="A")
B = gs.Point(1, 0)
B.plot(label="B")
s1 = gs.Seg(A, B)
s1.plot()
c2 = gs.Circle(A, A.distance(B))
c2.plot(speed=0, c="gray")
c3 = gs.Circle(B, A.distance(B))
c3.plot(speed=0, c="gray")
p1, p2 = c2.intersection(c3)
q1 = gs.Point(p1.x, p1.y)
q2 = gs.Point(p2.x, p2.y)
s2 = gs.Seg(q1, q2)
s2.plot()
p1, p2 = s2.intersection(c1)
C = gs.Point(p1.x, p1.y)
C.plot(label="C")
D = gs.Point(p2.x, p2.y)
D.plot(label="D")
c4 = gs.Circle(A, A.distance(O))
c4.plot(speed=0, c="gray")
p1, p2 = c4.intersection(c1)
q1 = gs.Point(p1.x, p1.y)
q2 = gs.Point(p2.x, p2.y)
s3 = gs.Seg(q1, q2)
s3.plot(c="gray")
p = s3.intersection(s1)[0]
E = gs.Point(p.x, p.y)
E.plot(label="E")
c5 = gs.Circle(E, C.distance(E))
c5.plot(speed=0)
p = c5.intersection(s1)[0]
F = gs.Point(p.x, p.y) # F((√5-1)/2,0)
F.plot(label="F", c="gold")
c6 = gs.Circle(C, C.distance(F))
c6.plot(speed=0)
p1, p2 = c6.intersection(c1)
P = gs.Point(p1.x, p1.y)
P.plot(label="P")
M = gs.Point(p2.x, p2.y)
M.plot(label="M")
c7 = gs.Circle(P, C.distance(P))
c7.plot(speed=0)
p1, p2 = c7.intersection(c1)
N = gs.Point(p2.x, p2.y)
N.plot(label="N")
c8 = gs.Circle(N, N.distance(P))
c8.plot(speed=0)
p1, p2 = c8.intersection(c1)
H = gs.Point(p2.x, p2.y)
H.plot(label="H")
s4 = gs.Seg(C, P)
s4.plot(c="red")
s5 = gs.Seg(P, N)
s5.plot(c="red")
s6 = gs.Seg(N, H)
s6.plot(c="red")
s7 = gs.Seg(H, M)
s7.plot(c="red")
s8 = gs.Seg(M, C)
s8.plot(c="red")
turtle.done()
