import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import turtle
import graphicssystem as gs

turtle.setup(720, 540)
turtle.setworldcoordinates(-4, -3, 4, 3)
A = gs.Point(0, 0)
A.plot(label="A")
c1 = gs.Circle(A, 1)
c1.plot()
B = gs.Point(-1, 0)
C = gs.Point(1, 0)
s1 = gs.Seg(B, C)
s1.plot()
B.plot(label="B")
C.plot(label="C")
c2 = gs.Circle(B, B.distance(C))
c2.plot()
c3 = gs.Circle(C, B.distance(C))
c3.plot()
p1, p2 = c2.intersection(c3)
D = gs.Point(p1.x, p1.y)
D.plot(label="D")
c4 = gs.Circle(C, A.distance(C))
c4.plot()
p1, p2 = c4.intersection(c1)
F = gs.Point(p1.x, p1.y)
F.plot(label="F")
E = gs.Point(p2.x, p2.y)
E.plot(label="E")
_, p = c2.intersection(c3)
q = gs.Point(p.x, p.y)
s2 = gs.Seg(D, q)
s2.plot()
p1, p2 = s2.intersection(c1)
G = gs.Point(p2.x, p2.y)
G.plot(label="G")
H = gs.Point(p1.x, p1.y)
H.plot(label="H")
s3 = gs.Seg(E, F)
s3.plot()
p = s3.intersection(s1)[0]
J = gs.Point(p.x, p.y)
J.plot(label="J")
s4 = gs.Seg(G, J)
s4.plot()
c5 = gs.Circle(J, A.distance(J))
c5.plot()
p = c5.intersection(s4)[0]
K = gs.Point(p.x, p.y)
K.plot(label="K")
c6 = gs.Circle(G, G.distance(K))
c6.plot()
p1, p2 = c6.intersection(c1)
M = gs.Point(p1.x, p1.y)
M.plot(label="M")
L = gs.Point(p2.x, p2.y)
L.plot(label="L")
c7 = gs.Circle(L, L.distance(G))
c7.plot()
p1, p2 = c7.intersection(c1)
R = gs.Point(p2.x, p2.y)
R.plot(label="R")
c8 = gs.Circle(M, M.distance(G))
c8.plot()
p1, p2 = c8.intersection(c1)
T = gs.Point(p2.x, p2.y)
T.plot(label="T")
r1 = gs.Ray(T, A)
p1, p2 = r1.intersection(c1)
I = gs.Point(p2.x, p2.y)
s5 = gs.Seg(T, I)
s5.plot()
I.plot(label="I")
r2 = gs.Ray(M, A)
p1, p2 = r2.intersection(c1)
P = gs.Point(p2.x, p2.y)
s6 = gs.Seg(M, P)
s6.plot()
P.plot(label="P")
r3 = gs.Ray(L, A)
p1, p2 = r3.intersection(c1)
Q = gs.Point(p2.x, p2.y)
s7 = gs.Seg(L, Q)
s7.plot()
Q.plot(label="Q")
r4 = gs.Ray(R, A)
p1, p2 = r4.intersection(c1)
U = gs.Point(p2.x, p2.y)
s8 = gs.Seg(R, U)
s8.plot()
U.plot(label="U")
points = [G, L, R, I, P, H, Q, U, T, M, G]
for i in range(10):
    gs.Seg(points[i], points[i+1]).plot(c="red")
turtle.done()
