import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import turtle
import graphicssystem as gs

turtle.setup(720, 540)
turtle.setworldcoordinates(-4, -3, 4, 3)
A = gs.Point(0, 0)
A.plot(label="A")
c1 = gs.Circle(A, 1)
c1.plot()
B = gs.Point(-1, 0)
B.plot(label="B")
C = gs.Point(1, 0)
C.plot(label="C")
s1 = gs.Seg(B, C)
s1.plot()
c2 = gs.Circle(B, B.distance(C))
c2.plot()
c3 = gs.Circle(C, B.distance(C))
c3.plot()
p1, p2 = c2.intersection(c3)
D = gs.Point(p1.x, p1.y)
D.plot(label="D")
c4 = gs.Circle(C, C.distance(A))
c4.plot()
p1, p2 = c4.intersection(c1)
F = gs.Point(p2.x, p2.y)
F.plot(label="F")
G = gs.Point(p1.x, p1.y)
G.plot(label="G")
s2 = gs.Seg(F, G)
s2.plot()
p = s2.intersection(s1)[0]
H = gs.Point(p.x, p.y)
H.plot(label="H")
s3 = gs.Seg(D, A)
s3.plot()
p = s3.intersection(c1)[0]
J = gs.Point(p.x, p.y)
J.plot(label="J")
c5 = gs.Circle(H, H.distance(J))
c5.plot()
p = c5.intersection(s1)[0]
K = gs.Point(p.x, p.y)
K.plot(label="K")
c6 = gs.Circle(K, A.distance(K))
c6.plot()
p1, p2 = c6.intersection(c1)
M = gs.Point(p2.x, p2.y)
M.plot(label="M")
L = gs.Point(p1.x, p1.y)
L.plot(label="L")
c7 = gs.Circle(C, L.distance(M))
c7.plot()
p1, p2 = c7.intersection(c1)
N = gs.Point(p1.x, p1.y)
N.plot(label="N")
P = gs.Point(p2.x, p2.y)
P.plot(label="P")
r1 = gs.Ray(M, A)
p1, p2 = r1.intersection(c1)
R = gs.Point(p1.x, p1.y)
s4 = gs.Seg(M, R)
s4.plot()
R.plot(label="R")
r2 = gs.Ray(N, A)
p1, p2 = r2.intersection(c1)
T = gs.Point(p2.x, p2.y)
s5 = gs.Seg(N, T)
s5.plot()
T.plot(label="T")
r3 = gs.Ray(P, A)
p1, p2 = r3.intersection(c1)
S = gs.Point(p1.x, p1.y)
s6 = gs.Seg(P, S)
s6.plot()
S.plot(label="S")
r4 = gs.Ray(L, A)
p1, p2 = r4.intersection(c1)
Q = gs.Point(p2.x, p2.y)
s7 = gs.Seg(L, Q)
s7.plot()
Q.plot(label="Q")
points = [S, N, R, C, Q, P, T, M, B, L, S]
for i in range(10):
    gs.Seg(points[i], points[i+1]).plot(c="red")
turtle.done()
