import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import turtle
import math
import sympy as sp
import graphicssystem as gs

turtle.setup(720, 701)
turtle.setworldcoordinates(-5/2, -2, 5/2, (math.sqrt(3)+4)/2)
A = gs.Point(0, 0)
A.plot(label="A")
c1 = gs.Circle(A, 1)
c1.plot()
B = gs.Point(sp.Rational(-1, 2), sp.sqrt(3)/2)
B.plot(label="B")
c2 = gs.Circle(B, 1)
c2.plot()
p1, p2 = c1.intersection(c2)
C = gs.Point(p1.x, p1.y)
C.plot(label="C")
D = gs.Point(p2.x, p2.y)
D.plot(label="D")
c3 = gs.Circle(D, float(A.distance(D)))
c3.plot()
p1, p2 = c1.intersection(c3)
E = gs.Point(p1.x, p1.y)
E.plot(label="E")
p1, p2 = c2.intersection(c3)
F = gs.Point(p2.x, p2.y)
F.plot(label="F")
r = gs.Ray(F, A)
p1, p2 = r.intersection(c1)
H = gs.Point(p1.x, p1.y)
s1 = gs.Seg(F, H)
s1.plot()
G = gs.Point(p2.x, p2.y)
G.plot(label="G")
H.plot(label="H")
s2 = gs.Seg(G, C)
s2.plot(c="red")
s3 = gs.Seg(C, H)
s3.plot(c="red")
s4 = gs.Seg(H, E)
s4.plot(c="red")
s5 = gs.Seg(E, G)
s5.plot(c="red")
turtle.done()
